name: Build DMG

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-dmg:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller dmgbuild

      - name: Build App Bundle with PyInstaller
        run: |
          # ※コード署名を行いたい場合は、--codesign-identity オプションなどを付与する
          pyinstaller --windowed --name "MyApp" main.py

      - name: Verify app bundle exists
        run: |
          ls -l dist/

      - name: Create DMG with dmgbuild
        run: |
          # dmgbuild の設定ファイル (settings.py) はリポジトリルートに配置済みであることを前提とします。
          dmgbuild -s settings.py "My App" MyApp.dmg

      - name: Display DMG Info
        run: |
          echo "DMG file created successfully at $(pwd)/MyApp.dmg"
          echo "File size: $(du -h MyApp.dmg | cut -f1)"

      # Create a simple HTML page with download link
      - name: Create Download Page
        run: |
          mkdir -p public
          cat > public/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>My App Download</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              .download-btn { display: inline-block; background-color: #4CAF50; color: white; padding: 10px 20px; 
                             text-decoration: none; border-radius: 4px; font-weight: bold; margin-top: 20px; }
              .download-btn:hover { background-color: #45a049; }
            </style>
          </head>
          <body>
            <h1>My App</h1>
            <p>A simple Python Tkinter application packaged as a DMG for macOS.</p>
            <p>Built on: $(date)</p>
            <p>File size: $(du -h MyApp.dmg | cut -f1)</p>
            <a class="download-btn" href="MyApp.dmg">Download DMG</a>
          </body>
          </html>
          EOF
          cp MyApp.dmg public/

      # Upload the download page and DMG as artifacts
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
